CREATE TABLE  "CONTA" 
   (	"NUMERO" NUMBER NOT NULL ENABLE, 
	"TIPO" VARCHAR2(1) NOT NULL ENABLE, 
	"SALDO" FLOAT(63) NOT NULL ENABLE, 
	"BONUS" NUMBER, 
	 PRIMARY KEY ("NUMERO") ENABLE
   )
/